<?php if(ale_get_option('twi')){ ?><a href="<?php echo esc_url(ale_get_option('twi')); ?>" class="twi" target="_blank"><?php echo esc_html_e('Twitter','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('fb')){ ?><a href="<?php echo esc_url(ale_get_option('fb')); ?>" class="fb" target="_blank"><?php echo esc_html_e('Facebook','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('you')){ ?><a href="<?php echo esc_url(ale_get_option('you')); ?>" class="you" target="_blank"><?php echo esc_html_e('Youtube','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('lin')){ ?><a href="<?php echo esc_url(ale_get_option('lin')); ?>" class="lin" target="_blank"><?php echo esc_html_e('LinkedIn','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('pin')){ ?><a href="<?php echo esc_url(ale_get_option('pin')); ?>" class="pin" target="_blank"><?php echo esc_html_e('Pinterest','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('gpl')){ ?><a href="<?php echo esc_url(ale_get_option('gpl')); ?>" class="gpl" target="_blank"><?php echo esc_html_e('Google+','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('tum')){ ?><a href="<?php echo esc_url(ale_get_option('tum')); ?>" class="tum" target="_blank"><?php echo esc_html_e('Tumblr','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('insta')){ ?><a href="<?php echo esc_url(ale_get_option('insta')); ?>" class="insta" target="_blank"><?php echo esc_html_e('Instagram','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('red')){ ?><a href="<?php echo esc_url(ale_get_option('red')); ?>" class="reddit" target="_blank"><?php echo esc_html_e('Reddit','gardener'); ?></a><?php } ?>
<?php if(ale_get_option('vk')){ ?><a href="<?php echo esc_url(ale_get_option('vk')); ?>" class="vk" target="_blank"><?php echo esc_html_e('VK','gardener'); ?></a><?php } ?>
